schemaVersion = 1

[extensions]
enabledIdentifiers = [ 'com.brnbw.tuna.plugins.notes', 'com.brnbw.tuna.plugins.obsidian', 'com.brnbw.tuna.plugins.reminders' ]

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 49
    carbonModifiers = 256

    [hotkeys.app.leaderMode]
    carbonKeyCode = 41
    carbonModifiers = 4096

[[leaderMode.bindings]]
iconPath = '/Applications/Ghostty.app'
key = 't'
label = 'Ghostty'
url = 'tuna://run/path.%252FApplications%252FGhostty.app/Open'

[[leaderMode.bindings]]
key = 'b'
label = 'Zen'
url = 'tuna://run/TunaCore.RunningProcessesCatalog.Zen/TunaCore.CommonActionsCatalog.Open'

[[leaderMode.bindings]]
key = 'f'
label = 'Finder'
url = 'tuna://run/path.%252FSystem%252FLibrary%252FCoreServices%252FFinder.app/Open'

[[leaderMode.bindings]]
iconPath = '/Applications/AeroSpace.app'
key = 'w'
label = 'Aerospace'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = 'a'
    label = 'workspace a'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%2520a/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = 's'
    label = 'workspace s'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%2520s/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = 'd'
    label = 'workspace d'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%2520d/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = 'f'
    label = 'workspace f'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%2520f/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = 'g'
    label = 'workspace g'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%2520g/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'arrow.trianglehead.merge'
    key = 'j'
    label = 'join-with'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'left'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520left/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'j'
        label = 'down'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520down/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'k'
        label = 'up'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520up/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'l'
        label = 'right'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520right/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'gearshift.layout.sixspeed'
    key = 'l'
    label = 'layout'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'h_accordion'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520h_accordion/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'v'
        label = 'v_accordion'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520v_accordion/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 't'
        label = 'tiles'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520tiles%2520horizontal%2520vertical/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'f'
        label = 'floating'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520floating%2520tiling/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        iconPath = 'desktopcomputer'
        key = 'F'
        label = 'fullscreen'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520fullscreen/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'move.3d'
    key = 'm'
    label = 'move'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'left'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520left/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'j'
        label = 'down'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520down/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'k'
        label = 'up'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520up/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'l'
        label = 'right'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520right/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'a'
        label = 'move-node-to-workspace a'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%2520a/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 's'
        label = 'move-node-to-workspace s'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%2520s/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'd'
        label = 'move-node-to-workspace d'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%2520d/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'f'
        label = 'move-node-to-workspace f'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%2520f/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'g'
        label = 'move-node-to-workspace g'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%2520g/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'square.resize'
    key = 'r'
    label = 'mode resize'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520mode%2520resize/Run%20Text%20as%20Shell%20Command'

[settings]
leaderModeBackspaceBehavior = 'stepBack'
leaderModeCheatsheetDelayMS = 250
leaderModeModifierTrigger = 'rightOption'
resultListNavigationBindings = 'vimStyle'
themeIdentifier = 'com.brnbw.tuna.themes.default'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'graphite'