schemaVersion = 1

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 49
    carbonModifiers = 256


[[leaderMode.bindings]]
key = 's'
url = 'tuna://run/path.%252FApplications%252FSafari.app/Open'

[[leaderMode.bindings]]
key = 't'
url = 'tuna://run/path.%252FSystem%252FApplications%252FUtilities%252FTerminal.app/Open'

[[leaderMode.bindings]]
key = 'f'
url = 'tuna://run/path.%252FSystem%252FLibrary%252FCoreServices%252FFinder.app/Open'

[[leaderMode.bindings]]
key = 'm'
url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

[[leaderMode.bindings]]
key = 'n'
url = 'tuna://run/path.%252FSystem%252FApplications%252FNotes.app/Open'

[[leaderMode.bindings]]
key = 'd'
url = 'tuna://run/path.%252FUsers%252Fnicolas%252FDownloads/Open'

[[leaderMode.bindings]]
key = 'h'
url = 'tuna://run/path.%252FUsers%252Fnicolas/Open'

[[leaderMode.bindings]]
iconPath = 'rectangle.grid.2x2'
key = 'w'
label = 'Aerospace'

    [[leaderMode.bindings.children]]
    key = '1'
    label = 'workspace 💬'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%2520%25F0%259F%2592%25AC/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = '2'
    label = 'workspace 🌐'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%2520%25F0%259F%258C%2590/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = '3'
    label = 'workspace 💻'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%2520%25F0%259F%2592%25BB/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = 'f'
    label = 'fullscreen'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520fullscreen/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = 'F'
    label = 'flatten-workspace-tree'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520flatten-workspace-tree/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = 'j'
    label = 'join-with'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'left'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520left/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'j'
        label = 'down'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520down/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'k'
        label = 'up'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520up/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'l'
        label = 'right'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520right/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = 'l'
    label = 'layout'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'h_accordion'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520h_accordion/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'v'
        label = 'v_accordion'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520v_accordion/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 't'
        label = 'tiles'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520tiles%2520horizontal%2520vertical/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'f'
        label = 'floating'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520floating%2520tiling/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = 'm'
    label = 'move'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'left'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520left/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'j'
        label = 'down'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520down/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'k'
        label = 'up'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520up/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'l'
        label = 'right'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520right/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '1'
        label = 'to 💬 + follow'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%2520%25F0%259F%2592%25AC/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '!'
        label = 'to 💬'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520%25F0%259F%2592%25AC/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '2'
        label = 'to 🌐 + follow'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%2520%25F0%259F%258C%2590/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '@'
        label = 'to 🌐'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520%25F0%259F%258C%2590/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '3'
        label = 'to 💻 + follow'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%2520%25F0%259F%2592%25BB/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '#'
        label = 'to 💻'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520%25F0%259F%2592%25BB/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = 's'
    label = 'mode resize'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520mode%2520resize/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    key = 'R'
    label = 'reload-config'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520reload-config/Run%20Text%20as%20Shell%20Command'

[settings]
leaderModeModifierTrigger = 'rightCommand'
resultListNavigationBindings = 'vimStyle'
themeIdentifier = 'com.brnbw.tuna.themes.default'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'graphite'