schemaVersion = 1

[hotkeys]
custom = []

    [hotkeys.app.activate]
    carbonKeyCode = 49
    carbonModifiers = 256

    [hotkeys.app.leaderMode]
    carbonKeyCode = 41
    carbonModifiers = 4096

[[leaderMode.bindings]]
iconPath = '/Applications/AeroSpace.app'
key = 'w'
label = 'Aerospace'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = '1'
    label = 'workspace 1'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%25201/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = '2'
    label = 'workspace 2'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%25202/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = '3'
    label = 'workspace 3'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%25203/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = '4'
    label = 'workspace 4'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520workspace%25204/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'square.resize'
    key = 'r'
    label = 'mode resize'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520mode%2520resize/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'desktopcomputer'
    key = 'f'
    label = 'fullscreen'
    url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520fullscreen/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'arrow.trianglehead.merge'
    key = 'j'
    label = 'join-with'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'left'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520left/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'j'
        label = 'down'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520down/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'k'
        label = 'up'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520up/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'l'
        label = 'right'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520join-with%2520right/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'gearshift.layout.sixspeed'
    key = 'l'
    label = 'layout'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'h_accordion'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520h_accordion/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'v'
        label = 'v_accordion'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520v_accordion/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 't'
        label = 'tiles'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520tiles%2520horizontal%2520vertical/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'f'
        label = 'floating'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520layout%2520floating%2520tiling/Run%20Text%20as%20Shell%20Command'

    [[leaderMode.bindings.children]]
    iconPath = 'move.3d'
    key = 'm'
    label = 'move'

        [[leaderMode.bindings.children.children]]
        key = 'h'
        label = 'left'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520left/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'j'
        label = 'down'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520down/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'k'
        label = 'up'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520up/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = 'l'
        label = 'right'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move%2520right/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '1'
        label = 'move-node-to-workspace 1'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%25201/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '2'
        label = 'move-node-to-workspace 2'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%25202/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '3'
        label = 'move-node-to-workspace 3'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%25203/Run%20Text%20as%20Shell%20Command'

        [[leaderMode.bindings.children.children]]
        key = '4'
        label = 'move-node-to-workspace 4'
        url = 'tuna://run/text.%252Fopt%252Fhomebrew%252Fbin%252Faerospace%2520move-node-to-workspace%2520--focus-follows-window%25204/Run%20Text%20as%20Shell%20Command'

[[leaderMode.bindings]]
iconPath = '/System/Applications/Utilities/Screenshot.app'
key = 's'
label = 'Screenshot'
url = 'tuna://run/Tuna.Internal.RecentObjectsCatalog.Screenshot/Open'

[[leaderMode.bindings]]
key = 'f'
label = 'Finder'
url = 'tuna://run/path.%252FSystem%252FLibrary%252FCoreServices%252FFinder.app/Open'

[[leaderMode.bindings]]
iconPath = '/Applications/Ghostty.app'
key = 't'
label = 'Terminal'
url = 'tuna://run/path.%252FApplications%252FGhostty.app/Open'

[[leaderMode.bindings]]
iconPath = '/Applications/Nix Apps/Zed.app'
key = 'e'
label = 'Editor'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Zed/Open'

[[leaderMode.bindings]]
iconPath = '/Applications/Zen.app'
key = 'b'
label = 'Browser'
url = 'tuna://run/Tuna.Internal.RecentObjectsCatalog.Zen/Open'

[settings]
leaderModeBackspaceBehavior = 'stepBack'
leaderModeCheatsheetDelayMS = 250
leaderModeModifierTrigger = 'rightOption'
resultListNavigationBindings = 'vimStyle'
themeIdentifier = 'com.brnbw.tuna.themes.default'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'graphite'